//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/GroupProject_Service")]
    public partial class User : object
    {
        
        private string EmailField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string PasswordField;
        
        private string PhoneField;
        
        private System.DateTime RegistrationDateField;
        
        private int userIdField;
        
        private string userTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegistrationDate
        {
            get
            {
                return this.RegistrationDateField;
            }
            set
            {
                this.RegistrationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userType
        {
            get
            {
                return this.userTypeField;
            }
            set
            {
                this.userTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/GroupProject_Service")]
    public partial class Product : object
    {
        
        private string BrandField;
        
        private string CategoryField;
        
        private string DescriptionField;
        
        private string ImageUrlField;
        
        private string NameField;
        
        private decimal PriceField;
        
        private System.Nullable<decimal> SalePriceField;
        
        private System.Nullable<int> StockQtyField;
        
        private bool isNewField;
        
        private bool onSaleField;
        
        private int productIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand
        {
            get
            {
                return this.BrandField;
            }
            set
            {
                this.BrandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl
        {
            get
            {
                return this.ImageUrlField;
            }
            set
            {
                this.ImageUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SalePrice
        {
            get
            {
                return this.SalePriceField;
            }
            set
            {
                this.SalePriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StockQty
        {
            get
            {
                return this.StockQtyField;
            }
            set
            {
                this.StockQtyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isNew
        {
            get
            {
                return this.isNewField;
            }
            set
            {
                this.isNewField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool onSale
        {
            get
            {
                return this.onSaleField;
            }
            set
            {
                this.onSaleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int productId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cart", Namespace="http://schemas.datacontract.org/2004/07/GroupProject_Service")]
    public partial class Cart : object
    {
        
        private int CartIdField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartId
        {
            get
            {
                return this.CartIdField;
            }
            set
            {
                this.CartIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartItem", Namespace="http://schemas.datacontract.org/2004/07/GroupProject_Service")]
    public partial class CartItem : object
    {
        
        private int CartIdField;
        
        private int ProductIdField;
        
        private int QtyAddedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartId
        {
            get
            {
                return this.CartIdField;
            }
            set
            {
                this.CartIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId
        {
            get
            {
                return this.ProductIdField;
            }
            set
            {
                this.ProductIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QtyAdded
        {
            get
            {
                return this.QtyAddedField;
            }
            set
            {
                this.QtyAddedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/GroupProject_Service")]
    public partial class Order : object
    {
        
        private System.DateTime DateField;
        
        private decimal OrderTotalField;
        
        private string StatusField;
        
        private int orderIdField;
        
        private int userIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OrderTotal
        {
            get
            {
                return this.OrderTotalField;
            }
            set
            {
                this.OrderTotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int orderId
        {
            get
            {
                return this.orderIdField;
            }
            set
            {
                this.orderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseProduct", Namespace="http://schemas.datacontract.org/2004/07/GroupProject_Service")]
    public partial class PurchaseProduct : object
    {
        
        private int QtyField;
        
        private int orderIdField;
        
        private int productIdField;
        
        private int purchasedPIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Qty
        {
            get
            {
                return this.QtyField;
            }
            set
            {
                this.QtyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int orderId
        {
            get
            {
                return this.orderIdField;
            }
            set
            {
                this.orderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int productId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int purchasedPId
        {
            get
            {
                return this.purchasedPIdField;
            }
            set
            {
                this.purchasedPIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invoice", Namespace="http://schemas.datacontract.org/2004/07/GroupProject_Service")]
    public partial class Invoice : object
    {
        
        private System.DateTime DateField;
        
        private bool StatusField;
        
        private decimal TotalField;
        
        private int invoiceIdField;
        
        private int orderIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int invoiceId
        {
            get
            {
                return this.invoiceIdField;
            }
            set
            {
                this.invoiceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int orderId
        {
            get
            {
                return this.orderIdField;
            }
            set
            {
                this.orderIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWebService")]
    public interface IWebService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/Register", ReplyAction="http://tempuri.org/IWebService/RegisterResponse")]
        bool Register(ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/Register", ReplyAction="http://tempuri.org/IWebService/RegisterResponse")]
        System.Threading.Tasks.Task<bool> RegisterAsync(ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/UserExists", ReplyAction="http://tempuri.org/IWebService/UserExistsResponse")]
        bool UserExists(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/UserExists", ReplyAction="http://tempuri.org/IWebService/UserExistsResponse")]
        System.Threading.Tasks.Task<bool> UserExistsAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/Login", ReplyAction="http://tempuri.org/IWebService/LoginResponse")]
        ServiceReference1.User Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/Login", ReplyAction="http://tempuri.org/IWebService/LoginResponse")]
        System.Threading.Tasks.Task<ServiceReference1.User> LoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetUserById", ReplyAction="http://tempuri.org/IWebService/GetUserByIdResponse")]
        ServiceReference1.User GetUserById(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetUserById", ReplyAction="http://tempuri.org/IWebService/GetUserByIdResponse")]
        System.Threading.Tasks.Task<ServiceReference1.User> GetUserByIdAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetNewCustomers", ReplyAction="http://tempuri.org/IWebService/GetNewCustomersResponse")]
        System.Collections.Generic.List<ServiceReference1.User> GetNewCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetNewCustomers", ReplyAction="http://tempuri.org/IWebService/GetNewCustomersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.User>> GetNewCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetProducts", ReplyAction="http://tempuri.org/IWebService/GetProductsResponse")]
        System.Collections.Generic.List<ServiceReference1.Product> GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetProducts", ReplyAction="http://tempuri.org/IWebService/GetProductsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetProductsOnSale", ReplyAction="http://tempuri.org/IWebService/GetProductsOnSaleResponse")]
        System.Collections.Generic.List<ServiceReference1.Product> GetProductsOnSale();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetProductsOnSale", ReplyAction="http://tempuri.org/IWebService/GetProductsOnSaleResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetProductsOnSaleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetFeaturedProducts", ReplyAction="http://tempuri.org/IWebService/GetFeaturedProductsResponse")]
        System.Collections.Generic.List<ServiceReference1.Product> GetFeaturedProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetFeaturedProducts", ReplyAction="http://tempuri.org/IWebService/GetFeaturedProductsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetFeaturedProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetProductByID", ReplyAction="http://tempuri.org/IWebService/GetProductByIDResponse")]
        ServiceReference1.Product GetProductByID(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetProductByID", ReplyAction="http://tempuri.org/IWebService/GetProductByIDResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Product> GetProductByIDAsync(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetProductsByCategory", ReplyAction="http://tempuri.org/IWebService/GetProductsByCategoryResponse")]
        System.Collections.Generic.List<ServiceReference1.Product> GetProductsByCategory(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetProductsByCategory", ReplyAction="http://tempuri.org/IWebService/GetProductsByCategoryResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetProductsByCategoryAsync(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetCategories", ReplyAction="http://tempuri.org/IWebService/GetCategoriesResponse")]
        System.Collections.Generic.List<string> GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetCategories", ReplyAction="http://tempuri.org/IWebService/GetCategoriesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/AddProduct", ReplyAction="http://tempuri.org/IWebService/AddProductResponse")]
        bool AddProduct(ServiceReference1.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/AddProduct", ReplyAction="http://tempuri.org/IWebService/AddProductResponse")]
        System.Threading.Tasks.Task<bool> AddProductAsync(ServiceReference1.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/EditProduct", ReplyAction="http://tempuri.org/IWebService/EditProductResponse")]
        bool EditProduct(ServiceReference1.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/EditProduct", ReplyAction="http://tempuri.org/IWebService/EditProductResponse")]
        System.Threading.Tasks.Task<bool> EditProductAsync(ServiceReference1.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/DeleteProduct", ReplyAction="http://tempuri.org/IWebService/DeleteProductResponse")]
        bool DeleteProduct(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/DeleteProduct", ReplyAction="http://tempuri.org/IWebService/DeleteProductResponse")]
        System.Threading.Tasks.Task<bool> DeleteProductAsync(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/AddToCart", ReplyAction="http://tempuri.org/IWebService/AddToCartResponse")]
        bool AddToCart(int userId, int productId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/AddToCart", ReplyAction="http://tempuri.org/IWebService/AddToCartResponse")]
        System.Threading.Tasks.Task<bool> AddToCartAsync(int userId, int productId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetCart", ReplyAction="http://tempuri.org/IWebService/GetCartResponse")]
        ServiceReference1.Cart GetCart(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetCart", ReplyAction="http://tempuri.org/IWebService/GetCartResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Cart> GetCartAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetCartItems", ReplyAction="http://tempuri.org/IWebService/GetCartItemsResponse")]
        System.Collections.Generic.List<ServiceReference1.CartItem> GetCartItems(int cartId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetCartItems", ReplyAction="http://tempuri.org/IWebService/GetCartItemsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.CartItem>> GetCartItemsAsync(int cartId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/RemoveFromCart", ReplyAction="http://tempuri.org/IWebService/RemoveFromCartResponse")]
        bool RemoveFromCart(int cartId, int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/RemoveFromCart", ReplyAction="http://tempuri.org/IWebService/RemoveFromCartResponse")]
        System.Threading.Tasks.Task<bool> RemoveFromCartAsync(int cartId, int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetCartTotalPrice", ReplyAction="http://tempuri.org/IWebService/GetCartTotalPriceResponse")]
        decimal GetCartTotalPrice(int cartId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetCartTotalPrice", ReplyAction="http://tempuri.org/IWebService/GetCartTotalPriceResponse")]
        System.Threading.Tasks.Task<decimal> GetCartTotalPriceAsync(int cartId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/AddToWishlist", ReplyAction="http://tempuri.org/IWebService/AddToWishlistResponse")]
        bool AddToWishlist(int userId, int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/AddToWishlist", ReplyAction="http://tempuri.org/IWebService/AddToWishlistResponse")]
        System.Threading.Tasks.Task<bool> AddToWishlistAsync(int userId, int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetWishlistItems", ReplyAction="http://tempuri.org/IWebService/GetWishlistItemsResponse")]
        System.Collections.Generic.List<ServiceReference1.Product> GetWishlistItems(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetWishlistItems", ReplyAction="http://tempuri.org/IWebService/GetWishlistItemsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetWishlistItemsAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/RemoveFromWishlist", ReplyAction="http://tempuri.org/IWebService/RemoveFromWishlistResponse")]
        bool RemoveFromWishlist(int userId, int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/RemoveFromWishlist", ReplyAction="http://tempuri.org/IWebService/RemoveFromWishlistResponse")]
        System.Threading.Tasks.Task<bool> RemoveFromWishlistAsync(int userId, int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/PlaceOrder", ReplyAction="http://tempuri.org/IWebService/PlaceOrderResponse")]
        int PlaceOrder(ServiceReference1.Order order, System.Collections.Generic.List<ServiceReference1.PurchaseProduct> purchasedProducts);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/PlaceOrder", ReplyAction="http://tempuri.org/IWebService/PlaceOrderResponse")]
        System.Threading.Tasks.Task<int> PlaceOrderAsync(ServiceReference1.Order order, System.Collections.Generic.List<ServiceReference1.PurchaseProduct> purchasedProducts);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GenerateInvoice", ReplyAction="http://tempuri.org/IWebService/GenerateInvoiceResponse")]
        ServiceReference1.Invoice GenerateInvoice(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GenerateInvoice", ReplyAction="http://tempuri.org/IWebService/GenerateInvoiceResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Invoice> GenerateInvoiceAsync(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetInvoiceByInvoiceID", ReplyAction="http://tempuri.org/IWebService/GetInvoiceByInvoiceIDResponse")]
        ServiceReference1.Invoice GetInvoiceByInvoiceID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetInvoiceByInvoiceID", ReplyAction="http://tempuri.org/IWebService/GetInvoiceByInvoiceIDResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Invoice> GetInvoiceByInvoiceIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetInvoicesByUserId", ReplyAction="http://tempuri.org/IWebService/GetInvoicesByUserIdResponse")]
        System.Collections.Generic.List<ServiceReference1.Invoice> GetInvoicesByUserId(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetInvoicesByUserId", ReplyAction="http://tempuri.org/IWebService/GetInvoicesByUserIdResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Invoice>> GetInvoicesByUserIdAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetProductsOnSaleByCategory", ReplyAction="http://tempuri.org/IWebService/GetProductsOnSaleByCategoryResponse")]
        System.Collections.Generic.List<ServiceReference1.Product> GetProductsOnSaleByCategory(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetProductsOnSaleByCategory", ReplyAction="http://tempuri.org/IWebService/GetProductsOnSaleByCategoryResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetProductsOnSaleByCategoryAsync(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetProductsByIDs", ReplyAction="http://tempuri.org/IWebService/GetProductsByIDsResponse")]
        System.Collections.Generic.List<ServiceReference1.Product> GetProductsByIDs(System.Collections.Generic.List<int> productIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetProductsByIDs", ReplyAction="http://tempuri.org/IWebService/GetProductsByIDsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetProductsByIDsAsync(System.Collections.Generic.List<int> productIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetOrderById", ReplyAction="http://tempuri.org/IWebService/GetOrderByIdResponse")]
        ServiceReference1.Order GetOrderById(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetOrderById", ReplyAction="http://tempuri.org/IWebService/GetOrderByIdResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Order> GetOrderByIdAsync(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetPurchasedProductsByOrderId", ReplyAction="http://tempuri.org/IWebService/GetPurchasedProductsByOrderIdResponse")]
        System.Collections.Generic.List<ServiceReference1.PurchaseProduct> GetPurchasedProductsByOrderId(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetPurchasedProductsByOrderId", ReplyAction="http://tempuri.org/IWebService/GetPurchasedProductsByOrderIdResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.PurchaseProduct>> GetPurchasedProductsByOrderIdAsync(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetPurchasedProducts", ReplyAction="http://tempuri.org/IWebService/GetPurchasedProductsResponse")]
        System.Collections.Generic.List<ServiceReference1.Product> GetPurchasedProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetPurchasedProducts", ReplyAction="http://tempuri.org/IWebService/GetPurchasedProductsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetPurchasedProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetNumberOfDifferentProductsSold", ReplyAction="http://tempuri.org/IWebService/GetNumberOfDifferentProductsSoldResponse")]
        int GetNumberOfDifferentProductsSold();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetNumberOfDifferentProductsSold", ReplyAction="http://tempuri.org/IWebService/GetNumberOfDifferentProductsSoldResponse")]
        System.Threading.Tasks.Task<int> GetNumberOfDifferentProductsSoldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetNumberOfRegisteredUsers", ReplyAction="http://tempuri.org/IWebService/GetNumberOfRegisteredUsersResponse")]
        int GetNumberOfRegisteredUsers(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetNumberOfRegisteredUsers", ReplyAction="http://tempuri.org/IWebService/GetNumberOfRegisteredUsersResponse")]
        System.Threading.Tasks.Task<int> GetNumberOfRegisteredUsersAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetNumberOfOrders", ReplyAction="http://tempuri.org/IWebService/GetNumberOfOrdersResponse")]
        int GetNumberOfOrders(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetNumberOfOrders", ReplyAction="http://tempuri.org/IWebService/GetNumberOfOrdersResponse")]
        System.Threading.Tasks.Task<int> GetNumberOfOrdersAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetTotalOrders", ReplyAction="http://tempuri.org/IWebService/GetTotalOrdersResponse")]
        int GetTotalOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetTotalOrders", ReplyAction="http://tempuri.org/IWebService/GetTotalOrdersResponse")]
        System.Threading.Tasks.Task<int> GetTotalOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetTotalRevenue", ReplyAction="http://tempuri.org/IWebService/GetTotalRevenueResponse")]
        decimal GetTotalRevenue();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetTotalRevenue", ReplyAction="http://tempuri.org/IWebService/GetTotalRevenueResponse")]
        System.Threading.Tasks.Task<decimal> GetTotalRevenueAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/AverageRevenuePerUser", ReplyAction="http://tempuri.org/IWebService/AverageRevenuePerUserResponse")]
        decimal AverageRevenuePerUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/AverageRevenuePerUser", ReplyAction="http://tempuri.org/IWebService/AverageRevenuePerUserResponse")]
        System.Threading.Tasks.Task<decimal> AverageRevenuePerUserAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IWebServiceChannel : ServiceReference1.IWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class WebServiceClient : System.ServiceModel.ClientBase<ServiceReference1.IWebService>, ServiceReference1.IWebService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebServiceClient() : 
                base(WebServiceClient.GetDefaultBinding(), WebServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IWebService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(WebServiceClient.GetBindingForEndpoint(endpointConfiguration), WebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool Register(ServiceReference1.User user)
        {
            return base.Channel.Register(user);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterAsync(ServiceReference1.User user)
        {
            return base.Channel.RegisterAsync(user);
        }
        
        public bool UserExists(string email)
        {
            return base.Channel.UserExists(email);
        }
        
        public System.Threading.Tasks.Task<bool> UserExistsAsync(string email)
        {
            return base.Channel.UserExistsAsync(email);
        }
        
        public ServiceReference1.User Login(string email, string password)
        {
            return base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.User> LoginAsync(string email, string password)
        {
            return base.Channel.LoginAsync(email, password);
        }
        
        public ServiceReference1.User GetUserById(int userId)
        {
            return base.Channel.GetUserById(userId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.User> GetUserByIdAsync(int userId)
        {
            return base.Channel.GetUserByIdAsync(userId);
        }
        
        public System.Collections.Generic.List<ServiceReference1.User> GetNewCustomers()
        {
            return base.Channel.GetNewCustomers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.User>> GetNewCustomersAsync()
        {
            return base.Channel.GetNewCustomersAsync();
        }
        
        public System.Collections.Generic.List<ServiceReference1.Product> GetProducts()
        {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetProductsAsync()
        {
            return base.Channel.GetProductsAsync();
        }
        
        public System.Collections.Generic.List<ServiceReference1.Product> GetProductsOnSale()
        {
            return base.Channel.GetProductsOnSale();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetProductsOnSaleAsync()
        {
            return base.Channel.GetProductsOnSaleAsync();
        }
        
        public System.Collections.Generic.List<ServiceReference1.Product> GetFeaturedProducts()
        {
            return base.Channel.GetFeaturedProducts();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetFeaturedProductsAsync()
        {
            return base.Channel.GetFeaturedProductsAsync();
        }
        
        public ServiceReference1.Product GetProductByID(int productId)
        {
            return base.Channel.GetProductByID(productId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Product> GetProductByIDAsync(int productId)
        {
            return base.Channel.GetProductByIDAsync(productId);
        }
        
        public System.Collections.Generic.List<ServiceReference1.Product> GetProductsByCategory(string category)
        {
            return base.Channel.GetProductsByCategory(category);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetProductsByCategoryAsync(string category)
        {
            return base.Channel.GetProductsByCategoryAsync(category);
        }
        
        public System.Collections.Generic.List<string> GetCategories()
        {
            return base.Channel.GetCategories();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetCategoriesAsync()
        {
            return base.Channel.GetCategoriesAsync();
        }
        
        public bool AddProduct(ServiceReference1.Product product)
        {
            return base.Channel.AddProduct(product);
        }
        
        public System.Threading.Tasks.Task<bool> AddProductAsync(ServiceReference1.Product product)
        {
            return base.Channel.AddProductAsync(product);
        }
        
        public bool EditProduct(ServiceReference1.Product product)
        {
            return base.Channel.EditProduct(product);
        }
        
        public System.Threading.Tasks.Task<bool> EditProductAsync(ServiceReference1.Product product)
        {
            return base.Channel.EditProductAsync(product);
        }
        
        public bool DeleteProduct(int productId)
        {
            return base.Channel.DeleteProduct(productId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteProductAsync(int productId)
        {
            return base.Channel.DeleteProductAsync(productId);
        }
        
        public bool AddToCart(int userId, int productId, int quantity)
        {
            return base.Channel.AddToCart(userId, productId, quantity);
        }
        
        public System.Threading.Tasks.Task<bool> AddToCartAsync(int userId, int productId, int quantity)
        {
            return base.Channel.AddToCartAsync(userId, productId, quantity);
        }
        
        public ServiceReference1.Cart GetCart(int userId)
        {
            return base.Channel.GetCart(userId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Cart> GetCartAsync(int userId)
        {
            return base.Channel.GetCartAsync(userId);
        }
        
        public System.Collections.Generic.List<ServiceReference1.CartItem> GetCartItems(int cartId)
        {
            return base.Channel.GetCartItems(cartId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.CartItem>> GetCartItemsAsync(int cartId)
        {
            return base.Channel.GetCartItemsAsync(cartId);
        }
        
        public bool RemoveFromCart(int cartId, int productId)
        {
            return base.Channel.RemoveFromCart(cartId, productId);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveFromCartAsync(int cartId, int productId)
        {
            return base.Channel.RemoveFromCartAsync(cartId, productId);
        }
        
        public decimal GetCartTotalPrice(int cartId)
        {
            return base.Channel.GetCartTotalPrice(cartId);
        }
        
        public System.Threading.Tasks.Task<decimal> GetCartTotalPriceAsync(int cartId)
        {
            return base.Channel.GetCartTotalPriceAsync(cartId);
        }
        
        public bool AddToWishlist(int userId, int productId)
        {
            return base.Channel.AddToWishlist(userId, productId);
        }
        
        public System.Threading.Tasks.Task<bool> AddToWishlistAsync(int userId, int productId)
        {
            return base.Channel.AddToWishlistAsync(userId, productId);
        }
        
        public System.Collections.Generic.List<ServiceReference1.Product> GetWishlistItems(int userId)
        {
            return base.Channel.GetWishlistItems(userId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetWishlistItemsAsync(int userId)
        {
            return base.Channel.GetWishlistItemsAsync(userId);
        }
        
        public bool RemoveFromWishlist(int userId, int productId)
        {
            return base.Channel.RemoveFromWishlist(userId, productId);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveFromWishlistAsync(int userId, int productId)
        {
            return base.Channel.RemoveFromWishlistAsync(userId, productId);
        }
        
        public int PlaceOrder(ServiceReference1.Order order, System.Collections.Generic.List<ServiceReference1.PurchaseProduct> purchasedProducts)
        {
            return base.Channel.PlaceOrder(order, purchasedProducts);
        }
        
        public System.Threading.Tasks.Task<int> PlaceOrderAsync(ServiceReference1.Order order, System.Collections.Generic.List<ServiceReference1.PurchaseProduct> purchasedProducts)
        {
            return base.Channel.PlaceOrderAsync(order, purchasedProducts);
        }
        
        public ServiceReference1.Invoice GenerateInvoice(int orderId)
        {
            return base.Channel.GenerateInvoice(orderId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Invoice> GenerateInvoiceAsync(int orderId)
        {
            return base.Channel.GenerateInvoiceAsync(orderId);
        }
        
        public ServiceReference1.Invoice GetInvoiceByInvoiceID(int id)
        {
            return base.Channel.GetInvoiceByInvoiceID(id);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Invoice> GetInvoiceByInvoiceIDAsync(int id)
        {
            return base.Channel.GetInvoiceByInvoiceIDAsync(id);
        }
        
        public System.Collections.Generic.List<ServiceReference1.Invoice> GetInvoicesByUserId(int userId)
        {
            return base.Channel.GetInvoicesByUserId(userId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Invoice>> GetInvoicesByUserIdAsync(int userId)
        {
            return base.Channel.GetInvoicesByUserIdAsync(userId);
        }
        
        public System.Collections.Generic.List<ServiceReference1.Product> GetProductsOnSaleByCategory(string category)
        {
            return base.Channel.GetProductsOnSaleByCategory(category);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetProductsOnSaleByCategoryAsync(string category)
        {
            return base.Channel.GetProductsOnSaleByCategoryAsync(category);
        }
        
        public System.Collections.Generic.List<ServiceReference1.Product> GetProductsByIDs(System.Collections.Generic.List<int> productIds)
        {
            return base.Channel.GetProductsByIDs(productIds);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetProductsByIDsAsync(System.Collections.Generic.List<int> productIds)
        {
            return base.Channel.GetProductsByIDsAsync(productIds);
        }
        
        public ServiceReference1.Order GetOrderById(int orderId)
        {
            return base.Channel.GetOrderById(orderId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Order> GetOrderByIdAsync(int orderId)
        {
            return base.Channel.GetOrderByIdAsync(orderId);
        }
        
        public System.Collections.Generic.List<ServiceReference1.PurchaseProduct> GetPurchasedProductsByOrderId(int orderId)
        {
            return base.Channel.GetPurchasedProductsByOrderId(orderId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.PurchaseProduct>> GetPurchasedProductsByOrderIdAsync(int orderId)
        {
            return base.Channel.GetPurchasedProductsByOrderIdAsync(orderId);
        }
        
        public System.Collections.Generic.List<ServiceReference1.Product> GetPurchasedProducts()
        {
            return base.Channel.GetPurchasedProducts();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Product>> GetPurchasedProductsAsync()
        {
            return base.Channel.GetPurchasedProductsAsync();
        }
        
        public int GetNumberOfDifferentProductsSold()
        {
            return base.Channel.GetNumberOfDifferentProductsSold();
        }
        
        public System.Threading.Tasks.Task<int> GetNumberOfDifferentProductsSoldAsync()
        {
            return base.Channel.GetNumberOfDifferentProductsSoldAsync();
        }
        
        public int GetNumberOfRegisteredUsers(System.DateTime date)
        {
            return base.Channel.GetNumberOfRegisteredUsers(date);
        }
        
        public System.Threading.Tasks.Task<int> GetNumberOfRegisteredUsersAsync(System.DateTime date)
        {
            return base.Channel.GetNumberOfRegisteredUsersAsync(date);
        }
        
        public int GetNumberOfOrders(System.DateTime date)
        {
            return base.Channel.GetNumberOfOrders(date);
        }
        
        public System.Threading.Tasks.Task<int> GetNumberOfOrdersAsync(System.DateTime date)
        {
            return base.Channel.GetNumberOfOrdersAsync(date);
        }
        
        public int GetTotalOrders()
        {
            return base.Channel.GetTotalOrders();
        }
        
        public System.Threading.Tasks.Task<int> GetTotalOrdersAsync()
        {
            return base.Channel.GetTotalOrdersAsync();
        }
        
        public decimal GetTotalRevenue()
        {
            return base.Channel.GetTotalRevenue();
        }
        
        public System.Threading.Tasks.Task<decimal> GetTotalRevenueAsync()
        {
            return base.Channel.GetTotalRevenueAsync();
        }
        
        public decimal AverageRevenuePerUser()
        {
            return base.Channel.AverageRevenuePerUser();
        }
        
        public System.Threading.Tasks.Task<decimal> AverageRevenuePerUserAsync()
        {
            return base.Channel.AverageRevenuePerUserAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWebService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWebService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:56432/WebService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WebServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IWebService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WebServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IWebService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IWebService,
        }
    }
}
